### ISSUE TITLE
Write blog posts in Jupyter notebooks

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy.org#130]
I noticed that the blog entries should be formatted as RST. Is there a way to submit a blog entry as a Jupyter notebook and have that automatically rendered? I think there are plugins for doing this on other blogging frameworks, e.g. [pelican](https://github.com/danielfrg/pelican-ipynb). Is there an equivalent plugin we could use? Writing posts in notebooks would make it easier to show off new features of the package

**Comment by wtbarnes** [comment]
Jupyter notebooks can be easily convert to RST using,

```bash
nbconvert --to rst my_notebook.ipynb
```
and the result actually looks pretty good and only requires minimal changes to get the website to build.

One issue: when images are included in the notebook and the notebook is converted, these images are dumped to a directory. In the website structure, how should these images be included? As a directory in the `posts/<year>` directory? 

It seems like the most ideal solution would be to support automatic conversion between notebooks and RST such that users could just submit a notebook as a PR.

**Comment by Cadair** [comment]
I agree, we should look into adding this as a feature to ablog.

**Comment by Cadair** [comment]
Actually, we just use sphinx, so I wonder how easy it would be to integrate ablog with 
http://nbsphinx.readthedocs.io/en/0.3.3/

**Comment by Cadair** [comment]
From a quick browse of the source code, it looks like nbsphinx is a fancy ipynb -> sphinx rst converter. So if we add the ablog post directive to a rst  code cell at the top of the notebook it might just work?!

**Comment by wtbarnes** [comment]
See #131. I pretty much just works.

**Comment by wtbarnes** [comment]
One minor problem: ablog treats the `.ipynb_checkpoints` file as a post and as a result renders the post twice. This is really only a problem when you're iterating on notebook. Is there some way to tell ablog to ignore certain files in the `posts` directory?

**Comment by wtbarnes** [comment]
Ignore my last comment. This is solved by just adding it to `exclude_patterns` in the `conf.py`. Sphinx is nice.
