### ISSUE TITLE
Add links to executable notebooks via Binder

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy.org#132]
Once #131 is merged, people can write blog posts as notebooks. It would be cool to take this one step further and provide a link to the notebook on [Binder](https://mybinder.org/) so that people can run the code for the blog entry in their browser as they are reading it.

See the [nbsphinx docs as an example](http://nbsphinx.readthedocs.io/en/0.3.3/prolog-and-epilog.html). I think this should be relatively straightforward. See the `nbsphinx_prolog` section nbsphinx config [Sphinx config file](https://github.com/spatialaudio/nbsphinx/blob/master/doc/conf.py).

This would be a good way to show off new features in SunPy without the user having to install anything.

I'm happy to put in a PR for this if people are on board.

**Comment by Cadair** [comment]
Oh yes!
