### ISSUE TITLE
Update donation link

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy.org#145]
Numfocus is changing the donation platform. All links directing to flipcause will stop working in mid-April. The new link is:

https://numfocus.salsalabs.org/donate-to-sunpy/index.html

I only found it on this repo, but we may also have on some other places.

**Comment by lisamartin72** [comment]
Hi there,

I was just going to submit a pull request with the new link from Salsa, but it looks like you are on top of it. : )

Thank you!

Lisa Martin
NumFOCUS.org
