### ISSUE TITLE
Current Version on home screen is ambiguous

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy.org#155]
Current stable version or similar might be a little more accurate

**Comment by nabobalis** [comment]
Fixed this by mistake.

**Comment by nabobalis** [comment]
NOT FIXED NEEDS TO BE CHANGED HERE:

https://github.com/sunpy/sunpy-sphinx-theme/blob/master/sunpy_sphinx_theme/sunpy/static/version.js

**Comment by nabobalis** [comment]
or we should make that return just the version number instead of overwriting the text.

**Comment by Cadair** [comment]
> or we should make that return just the version number instead of overwriting the text.

this seems like a good idea.
