### ISSUE TITLE
Add link to Board meeting minutes on website

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy.org#195]
It would be nice to have a link to the [meeting minutes](https://github.com/sunpy/sunpy/wiki/Home%3A-Organization-Information#minutes-of-sunpy-board-meetings) on the [project page](https://sunpy.org/team.html#sunpy-board), to increase their visibility.

**Comment by Cadair** [comment]
:+1: 
tbh, the project page needs a tidy up, but this is a good idea.

The index was also out of date, I updated it.

**Comment by nabobalis** [comment]
Should we go further and move them here?
