### ISSUE TITLE
Change the SunPy Project tab to expand and add an affiliated package tab and update list to cards

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy.org#196]
This would provide more and much needed prominence to affiliated packages.

**Comment by Cadair** [comment]
I am reluctant to add anything to the top nav bar. We had some discussions about developing a shared top level tree with a lot of the other numfocus projects at the summit, also too many options there would be detrimental.

+1 for the cards and generally changing things around to promote the affiliated packages though.

**Comment by ehsteve** [comment]
The problem is that we have too much under the easily confusiung heading "SunPy project". Can we have the headings expand out and have sub-headings?

**Comment by Cadair** [comment]
yeah, we already have that for the documentation heading, so it's certainly possible.

**Comment by ehsteve** [comment]
Let's do that then!
