### ISSUE TITLE
remove white spaces around the header image of sunpy.org website

### ISSUE THREAD

**Issue by iamrajiv** [sunpy/sunpy.org#201]
Currently, `https://sunpy.org/` site has a header image with white spaces around it. The header image is of SunPy logo.

![sunpy](https://user-images.githubusercontent.com/42106787/70243029-dd636280-1797-11ea-9e68-fa925434069c.JPG)

I think the header logo whiteout white spaces as around it will look great. Like this

![1](https://user-images.githubusercontent.com/42106787/70243679-1223e980-1799-11ea-8af8-afa631e7526c.JPG)

**Comment by iamrajiv** [comment]
I want to work on this issue

**Comment by nabobalis** [comment]
Go ahead.

**Comment by iamrajiv** [comment]
hey, @nabobalis since after `make html` it creates `_build` folder and inside `_build\html\_static` folder there is `favicon-32.ico` image which is converted by help of  `sunpy_icon.svg` image. I don't know where is code for conversion, I have searched `bootstrap` files but didn't get anything can you help me out with this

**Comment by nabobalis** [comment]
The code for this conversion is probably in an upstream package and not contained within any SunPy package. 

The source for the favicon comes from: https://github.com/sunpy/sunpy-sphinx-theme

**Comment by iamrajiv** [comment]
yeah @nabobalis source for the favicon and svg come from `sunpy-sphinx-theme` and it is in the `sunpy_sphinx_theme\confy.py` but full conversion code is not there it's only giving the name of the image in which it has to be converted i.e. `favicon-32.ico`
```
html_theme_path = get_html_theme_path()
html_theme = "sunpy"
html_static_path = [os.path.join(html_theme_path[0], html_theme, "static")]
templates_path = [os.path.join(html_theme_path[0], html_theme, "templates")]
html_favicon = os.path.join(html_static_path[0], "img", "favicon-32.ico")
```

**Comment by nabobalis** [comment]
Yeah, the conversion is done by either sphinx or some related package. We don't control that. 

Does it even convert the image and just not add it directly?

**Comment by iamrajiv** [comment]
@nabobalis yeah I think sphinx uses `ImageMagick` extensions to convert the images. It converts the image because there is only one image i.e. `sunpy_icon.svg`. Also in `theme.conf` file of `sunpy-sphinx-theme` its given this
```
# Defaults for SunPy projects
logo_url = https://sunpy.org/
opengraph_image = img/sunpy_icon.svg
twitter_id = sunpyproject
github_user = sunpy
github_repo = sunpy
social_buttons = True
```

**Comment by nabobalis** [comment]
Well the favicon which forms the icon for the tab name is a white background image. So would you not need to change that?

**Comment by iamrajiv** [comment]
We can't change that because it is generated every time when we `make html` and that `.ico` image is generated by `sunpy_icon.svg` image which is without background. The problem is with conversion package it converts `.svg` to `.ico` but did not maintain the transparent background for `.ico` that's why `favicon-32.ico` has a white background. @nabobalis

**Comment by nabobalis** [comment]
`html_favicon = os.path.join(html_static_path[0], "img", "favicon-32.ico")` should suggest that it comes not from the svg but from the favicon we have stored in the theme?

**Comment by iamrajiv** [comment]
I got it thanks @nabobalis

**Comment by iamrajiv** [comment]
got it thanks @nabobalis

**Comment by nabobalis** [comment]
So what will you do now?

**Comment by iamrajiv** [comment]
@nabobalis I have searched a lot but the problem is not with any SunPy packages I think it's related to `sphinx-bootstrap-theme` which has been imported in `sunpy-sphinx-theme` in `sunpy-sphinx-theme\sunpy_sphinx_theme\sunpy\__init__.py` file. What I think is we can manually convert `sunpy_icon.svg` to `.ico` and put it in header image

**Comment by nabobalis** [comment]
In that case, I will close this issue. Thanks for having a look at this!

**Comment by iamrajiv** [comment]
> In that case, I will close this issue. Thanks for having a look at this!

sure and thank you for guidance @nabobalis :grinning:

**Comment by iamrajiv** [comment]
@nabobalis I get to know that there is `sunpy_icon_128x128.png` and `favicon.ico` in folder `SunPy` at `sunpy/docs/logo` directory and I think changing these two files means removing the white background will help to solve this issue. But how to check this locally?

**Comment by nabobalis** [comment]
You'd have to change those files and rebuild either the website or the documentation.

**Comment by nabobalis** [comment]
How to do that for the website is in the readme and to build the docs is in the dev guide on the documentation website for sunpy.
