### ISSUE TITLE
code written in testing dependencies under testing framework  should be valid

### ISSUE THREAD

**Issue by mridullpandey** [sunpy/sunpy.org#207]
code for installing testing packages using pip should be  : pip install -e .[tests], instead of "pip intall -e .[tests]".

**Comment by nabobalis** [comment]
Where is this text?

**Comment by nabobalis** [comment]
Do you mean this? https://docs.sunpy.org/en/latest/dev_guide/tests.html#testing-dependencies

**Comment by nabobalis** [comment]
I will fix this now. Thanks for pointing it out.
