### ISSUE TITLE
Citation information is stale

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy.org#210]
Even though we've updated the citation info in [sunpy/sunpy/CITATION.rst](https://github.com/sunpy/sunpy/blob/master/sunpy/CITATION.rst) with the most recent ApJ and JOSS papers, the [old citation entry](https://sunpy.org/about#acknowledging-or-citing-sunpy) is still showing up on the rendered webpage. Not sure why that is...

**Comment by nabobalis** [comment]
Did we rebuild the website since we updated it?

**Comment by Cadair** [comment]
```
11:03:18 AM: Warning, treated as error:
11:03:18 AM: CITATION.rst:36:Title level inconsistent:
11:03:18 AM: Other SunPy publications
11:03:18 AM: ------------------------
11:03:18 AM: Makefile:20: recipe for target 'html' failed
11:03:18 AM: make: *** [html] Error 2
```

The new CITATION file has broken the build :man_facepalming:

**Comment by nabobalis** [comment]
We should make error if that happens.

**Comment by Cadair** [comment]
the build does error, it is just not a PR to the site, so we never saw it.

**Comment by nabobalis** [comment]
> the build does error, it is just not a PR to the site, so we never saw it.

We should make it email someone.
