### ISSUE TITLE
Submit NDCube for Review as An Affiliated Package

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy.org#216]
## Package Details

- Package name: NDCube
- Maintainer(s): Dan Ryan, Stuart Mumford
- Repository: https://github.com/sunpy/ndcube
- PyPI link: https://pypi.org/project/ndcube/

## Description of Package

NDCube is a general package for representing coordinate aware datasets. Built on Astropy and SunPy it provides users an easy to understand interface while keeping array data and coordinate data together to enabled physically meaningful analysis.

## Editor Submission Checklist

- [x] Is the submission appropriate?
- [x] Does the project have an OSI approved license?
- [x] Is the project in a version control repository?
- [x] Does the project provide a Python interface?
- [x] Is the project on PyPI?
- [x] Is the project useful to the solar physics community?

## Instructions to Reviewer

Please copy the following and select the ranking for each criteria, the full review criteria can be found here: https://deploy-preview-215--sunpy.netlify.app/project/affiliated#review-criteria

```
* Relevant and Useful Functionality    : General Package / Specalized Package / Not Relevant
* Make use of all appropriate features : Well integrated / Partially Integrated / Minimal Integration
* Documentation                        : Extensive / Some / Little
* Testing                              : Excellent / Good / Needs Work
* Duplication                          : Excellent / Good / Needs Work
* Community Engagement                 : Excellent / Good / Needs Work
* Maturity and Development Status      : Excellent / Good / Needs Work
```

**Comment by Cadair** [comment]
(I am submitting this, and also acting as editor as a demonstration of the system. [The Affiliated package liaison is the editor for this, but we don't have one so it's my job]).

**Comment by Cadair** [comment]
@SolarDrew Would you be able to review this submission?

**Comment by SolarDrew** [comment]
* Relevant and Useful Functionality    : General Package
* Make use of all appropriate features : Well integrated
* Documentation                        : Extensive
* Testing                              : Good
* Duplication                          : Excellent
* Community Engagement                 : Excellent
* Maturity and Development Status      : Excellent

Note that I've only not given excellent for the tests because the coverage is only at 60%.

**Comment by Cadair** [comment]
<author hat>

Did you look at the coverage for master or for the current release branch? Master is currently undergoing a massive rewrite so the test coverage for the Sequence plotting is almost non-existent as we haven't rewritten the code yet.

The coverage for the latest release is 95% https://codecov.io/gh/sunpy/ndcube/tree/fc69634a34dec246008652815b3c308e4e3325d2/ndcube

**Comment by SolarDrew** [comment]
Ah ok. Yes I was looking at the coverage on master but if the release coverage is much higher then I'm happy to take that and upgrade the score for that.

**Comment by SolarDrew** [comment]
* Relevant and Useful Functionality    : General Package
* Make use of all appropriate features : Well integrated
* Documentation                                  : Extensive
* Testing                                               : Excellent
* Duplication                                         : Excellent
* Community Engagement                   : Excellent
* Maturity and Development Status      : Excellent

**Comment by Cadair** [comment]
`<editor hat>`

Thanks for the review @SolarDrew :smile: 

Based on the review, NDCube will be accepted and added to the page, either @Cadair or I can open the PR to add it to the website :rofl:
