### ISSUE TITLE
Submit aiapy for review as an Affiliated Package

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy.org#220]
## Package Details

- Package name: aiapy
- Maintainer(s): Will Barnes, Mark Cheung
- Repository: https://gitlab.com/LMSAL_HUB/aia_hub/aiapy
- PyPI link (if applicable): https://pypi.org/project/aiapy/

## Description of Package

aiapy is a Python package for analyzing data from the Atmospheric Imaging
Assembly (AIA) instrument onboard NASA's Solar Dynamics Observatory
spacecraft.

## Editor Submission Checklist

- [x] Is the submission appropriate?
- [x] Does the project have an appropriate license?
- [x] Is the project in a version control repository?
- [x] Does the project provide a Python interface?
- [x] Is the project on PyPI?
- [x] Is the project useful to the solar physics community?

## Instructions to Reviewer

Please copy the following and select the ranking for each criteria, the full review criteria can be found here: 

```
* Functionality           : General Package / Specialized Package / Not Relevant
* Integration             : Well integrated / Partially Integrated / Minimal Integration
* Documentation           : Extensive / Some / Little
* Testing                 : Excellent / Good / Needs Work
* Duplication             : None / Some / Major
* Community               : Excellent / Good / Needs Work
* Development Status      : Stable / Rapid Development / Low Activity / Needs Work
```

**Comment by Cadair** [comment]
@nabobalis Would you be able to review this for me?

**Comment by nabobalis** [comment]
10/10 would aiapy again.

**Comment by nabobalis** [comment]
* Functionality           : Specialized Package
* Integration             : Well integrated
* Documentation           : Extensive
* Testing                 : Good (seems to have most functions covered)
* Duplication             : None (I wasn't able to see any)
* Community               :  Good (This is hard to judge)
* Development Status      : Rapid Development (I assume)

**Comment by Cadair** [comment]
@wtbarnes / @nabobalis I can't see a reference to a Code of Conduct anywhere in the aiapy docs or repo. Am I missing it? (it's a requirement for the community section)

**Comment by nabobalis** [comment]
I probably missed it.

**Comment by wtbarnes** [comment]
Oops 😬

**Comment by wtbarnes** [comment]
https://gitlab.com/LMSAL_HUB/aia_hub/aiapy/-/merge_requests/64

**Comment by wtbarnes** [comment]
the pycodestyle test is complaining about formatting in the CoC file 🤣
