### ISSUE TITLE
Submit sunkit-image for review as an Affiliated Package

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy.org#221]
## Package Details

- Package name: sunkit-image
- Maintainer(s): No one
- Repository: https://github.com/sunpy/sunkit-image
- PyPI link (if applicable): https://pypi.org/project/sunkit-image/

## Description of Package

sunkit-image is a a open-source toolbox for solar physics image processing. Currently it is experimental library for various solar physics specific image processing routines.

## Editor Submission Checklist

- [x] Is the submission appropriate?
- [x] Does the project have an appropriate license?
- [x] Is the project in a version control repository?
- [x] Does the project provide a Python interface?
- [x] Is the project on PyPI?
- [x] Is the project useful to the solar physics community?

## Instructions to Reviewer

Please copy the following and select the ranking for each criteria, the full review criteria can be found here: 

```
* Functionality           : General Package / Specialized Package / Not Relevant
* Integration             : Well integrated / Partially Integrated / Minimal Integration
* Documentation           : Extensive / Some / Little
* Testing                 : Excellent / Good / Needs Work
* Duplication             : None / Some / Major
* Community               : Excellent / Good / Needs Work
* Development Status      : Stable / Rapid Development / Low Activity / Needs Work
```

**Comment by hayesla** [comment]
* **Functionality**           : General Package
The functionality can be used by many in the solar physics community that use image data

* **Integration**            : Well integrated 
However lots of room to be further integrated - with further use of sunpy.map.Map and coordinates especially in coronal loops tracing in `sunkit_image.trace`

* **Documentation**           :  Some
Some - more needed. The docs aren’t linked on the github repo and somewhat difficult to find. A description of what sunkit-image is would be good, and more code reference, and user docs for the functionality available

*  **Testing**                 : Excellent
Majority of code-base covered. Not all functionality in `sunkit_image.radial` as far as I can see 

*  **Duplication**             : None 
Not as far as I can tell

*  **Community**               : Excellent 
I guess the community here is the SunPy community 🌞 

*  **Development Status**      :Rapid Development / Low Activity
The package is still openly being developed, however activity seems small

**Comment by Cadair** [comment]
@hayesla given the changes to the Integration section before the merge of the guidelines (and the text of your review) would you like to take another look at that or are you happy with it as it is?

**Comment by Cadair** [comment]
Also maybe docs as well given that got an extra tier.

**Comment by hayesla** [comment]
I would potentially change the Integration to Partial Integration tag. And Documentation I would change to Good.

**Comment by Cadair** [comment]
ooi what things do you see that could be more integrated? We should open issues for them :grinning:
