### ISSUE TITLE
Release Announcements etc for 2.0

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy.org#224]
(Opening against the website repo to cover various different things).

The following is a list of "major events" in the sunpy family around the 2.0 release. Not sure exactly how we want to take this list and turn it into things to shout about but:

# SunPy 2.0

This is the second LTS (supported for 1 year) release of SunPy, the "What's New" is in progress here: sunpy/sunpy#4040.

# Affiliated Package Process

We have the new process for reviewing and listing affiliated and sponsored packages here: sunpy/sunpy.org#214

We will hopefully have a pretty well populated list of packages shortly after we get the process merged in.

# First Releases of Affiliated Packages

The following packages have seen their first release recently:

1. aiapy (including moving `aiaprep` from sunpy core into aiapy)
1. sunkit-image
1. pyflct
1. sunraster (needs an issue opened for review)

# Other

Other related goings on I can think of:

1. GSOC (3 students, Glue, Fido and sunspotter)
1. We applied for GSOD (Google season of docs)

**Comment by Cadair** [comment]
@drsophiemurray Have you got thoughts on what we want to do about all this :grin:

**Comment by drsophiemurray** [comment]
> @drsophiemurray Have you got thoughts on what we want to do about all this 😁

Should definitely advertise widely on the usual mailing lists and social media. Theres a few extra I have in mind too that I haven't seen used before. Advertise but also highlight how people can ask questions and get involved!

I think we could also get a nice series of blog posts out about this. One announcing 2.0 obviously but then we can showcase each of the packages, and finish with a 'how-to' re: creating an affiliated package.

**Comment by dpshelio** [comment]
Do we want also to use this announcement to remember that we are looking to contract someone? (or so it says in the latest Numfocus newsletter).
