### ISSUE TITLE
Submit sunraster to be included as an affiliated package

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy.org#225]
## Package Details

- Package name: suntraster
- Maintainer(s): Dan Ryan
- Repository: https://github.com/sunpy/sunraster
- PyPI link (if applicable): https://pypi.org/project/sunraster/
- Documentation link (if applicable): https://docs.sunpy.org/projects/sunraster/
- Continuous integration link(s) (if applicable): https://dev.azure.com/sunpy/sunraster/ & https://circleci.com/gh/sunpy/sunraster/

## Description of Package
sunraster is a package designed for reading, manipulating and visualizing data taken with slit spectrograph instruments.

## Editor Submission Checklist

- [x] Is the submission appropriate (compatible with the SunPy CoC)?
- [x] Does the project have an appropriate license?
- [x] Is the project in a version control repository?
- [x] Does the project provide a Python interface?
- [x] Is the project on PyPI?
- [x] Is the project useful to the solar physics community?

## Instructions to Reviewer

Please copy the following and select the ranking for each criteria, the full review criteria can be found here: https://deploy-preview-215--sunpy.netlify.app/project/affiliated#affiliated-package-review-process

```
* Functionality           : General Package / Specialized Package / Not Relevant
* Integration             : Well integrated / Partially Integrated / Minimal Integration
* Documentation           : Extensive / Some / Little
* Testing                 : Excellent / Good / Needs Work
* Duplication             : None / Some / Major
* Community               : Excellent / Good / Needs Work
* Development Status      : Stable / Subject to Change / Low Activity / Needs Work

**Comment by Cadair** [comment]
@dstansby can you review this? :smiley:

**Comment by dstansby** [comment]
👍  - I will do the review once the review guidelines are finalised and merged

**Comment by Cadair** [comment]
They are now merged.

**Comment by dstansby** [comment]
* Functionality           : Specialized Package
* Integration             : Well integrated
Builds well on NDCube, uses `astropy.units` where appropriate
* Documentation           :  Some 
Good API documentation exists, but currently lacking an example gallery/tutorials that explain how the classes and functions could be used in real-world scientific applications.
* Testing                 :  Good
Not obvious what the code coverage is, and an automated coverage service (ie. codecov/coveralls) doesn't seem to be in use at the moment. Some functionality tests exist however, and these are automatically run with Azure.
* Duplication             : None
As far as I know no other package implements rastering-spectrograph specific functionality on top of NDCube.
* Community               : Excellent
Being developed actively in consultation with others in the solar physics python community, and good efforts have been made to engage a wide range of scientists working with rastering instruments.
* Development Status      : Subject to Change
pre-1.0, but active development is ongoing.
