### ISSUE TITLE
Affiliated package review criteria summary confusing

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy.org#230]
In the review criteria we say 

Accepted | Must have a green score in the Relevant and Useful criteria and at least one other. They must also have no red scores.
-- | --

However there are no **Relevant** and **Useful** criteria?

Should this just be **Functionality**?

**Comment by Cadair** [comment]
looks like it

**Comment by ayshih** [comment]
Just because I can, here's my comment from the PR:

> There are no "relevant and useful categories", just the "functionality" criterion?  I don't know whether "both" here is intended to refer to the "functionality" criterion *and* some other criterion that got edited out.

_Originally posted by @ayshih in https://github.com/sunpy/sunpy.org/pull/215#discussion_r418003388

**Comment by hayesla** [comment]
Ok, should it just be **Functionality** then? I'll make a PR after PyHC call

**Comment by Cadair** [comment]
I thought I fixed this before I merged it, but clearly didn't.

**Comment by wtbarnes** [comment]
Fixed by #231
