### ISSUE TITLE
Add pythia as an affiliated package!

### ISSUE THREAD

**Issue by Raahul-Singh** [sunpy/sunpy.org#239]
[Pythia](https://github.com/Raahul-Singh/pythia) has grown beyond the original scope of the GSoC project. Now, we are planning on making it into a general Deep Learning project for Solar Physics.

The generalisation is in progress and I will add some usage examples soon!

## Package Details

- Package name: Pythia
- Maintainer(s): Raahul Singh
- Repository: [pythia](https://github.com/Raahul-Singh/pythia)
- Documentation link: RTD on the way!
- PyPI link (if applicable): V0.1 yet to be published
- Continuous integration link(s): Github Actions : [codestyle](https://github.com/Raahul-Singh/pythia/blob/master/.github/workflows/codestyle.yml) and [pythonapp](https://github.com/Raahul-Singh/pythia/blob/master/.github/workflows/pythonapp.yml)
- Link to Code of Conduct or page describing adopted Code of Conduct: I will add this, shall I model it after SunPy's?

## Description of Package

Pythia initially started out as a repository for analysing Sunspotter dataset. Since then, powered by PyTorch Lightning, it has grown in a more general framework for Deep Learning in Solar Physics.
It's a WIP in terms of generalisation, but the end goal is to have a SciKit Learn like interface with the power of modern Deep Learning techniques.

There is a high barrier to entry for researchers not acquainted with modern DL frameworks.
Pythia seeks to break down these walls!

## Editor Submission Checklist

- [ ] Is the submission appropriate (compatible with the SunPy CoC)?
- [ ] Does the project have an [appropriate license](https://opensource.org/licenses/)?
- [ ] Is the project in an online version control system?
- [ ] Does the project provide a Python interface?
- [ ] Is the project on PyPI?
- [ ] Is the project useful to the solar physics community?

## Instructions to Reviewer

Please copy the following and select the ranking for each criteria, the full review criteria can be found here: 

```
* Functionality           : General Package / Specialized Package / Not Relevant
* Integration             : Well integrated / Partially Integrated / Minimal Integration
* Documentation           : Extensive / Some / Little
* Testing                 : Excellent / Good / Needs Work
* Duplication             : None / Some / Major
* Community               : Excellent / Good / Needs Work
* Development Status      : Stable / Subject to Change / Low Activity / Needs Work
```

**Comment by hayesla** [comment]
Cool - do you want to fill in the template information here?

**Comment by Raahul-Singh** [comment]
Yep let me just do that

**Comment by hayesla** [comment]
Great thanks for updating @Raahul-Singh !

**Comment by dstansby** [comment]
@Raahul-Singh sorry this has not gone anywhere - are you still interested in applying for affiliated package status review? If not we can close this issue, if so we will try and find a reviewer as soon as possible.

**Comment by Raahul-Singh** [comment]
> @Raahul-Singh sorry this has not gone anywhere - are you still interested in applying for affiliated package status review? If not we can close this issue, if so we will try and find a reviewer as soon as possible.

Hey @dstansby !
I don't think the package as it is right now has any users.
With that in mind, I think we can close this issue. However, if there is a use case for ML based packages in sunpy or open astronomy at large, I'd love to overhaul pythia to support them!
