### ISSUE TITLE
Explicitly state policy on reevaluation of affiliated packages

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy.org#242]
Given the debacle of #240, we need a policy regarding how affiliated package maintainers can request a reevaluation of their package. For example, if the documentation or testing has dramatically improved on a timescale shorter than 1 year (the interval over which the package would automatically be reevaluated), the developers may wish for the package to be reevaluated in those categories.

Currently, the only policy we have on reevaluation is that the packages will be reevaluated once a year to make sure they are being actively maintained (at least) at the standard at which they were originally evaluated.

A possible reevaluation could go as follows: affiliated package developer requests a reevaluation via an issue, indicating which categories they would like to be reevaluated in. If possible, the original reviewer of the affiliated package would be asked to reevaluate the package on the selected criteria. If the original reviewer is not available, another (impartial) reviewer will be selected in their place. The review criteria then proceeds as usual. If the reviewer finds that changes to any of the selected categories are needed (this could include downgrading the package in those categories as well), a PR is created (not by the affiliated package maintainer) to the webpage to make those changes.

This interim reevaluation would not be a substitute for the already established annual reevaluation.

**Comment by Cadair** [comment]
A quick bunch of things I have thought of without thinking too hard:

- Would the review be scoped tightly to the request, or could the reviewer change any rating (up or down)? What if a different reviewer disagrees with the original one?
 
- How easy should we make this process? Depending on how often this might happen it could quite substantially increase the workload on reviewers and editors.

**Comment by dstansby** [comment]
Being able to request re-evaluation, with supporting evidence provided with the request, seems a good policy. I think the review should be tightly scoped to the request.
> Would the review be scoped tightly to the request, or could the reviewer change any rating (up or down)? What if a different reviewer disagrees with the original one?

"If reviewers disagree" is a problem with the normal system anyway, so not sure that's relevant.
Hopefully in practice if someone is submitting a review request the rating won't go down...

> How easy should we make this process? Depending on how often this might happen it could quite substantially increase the workload on reviewers and editors.

The burden should be on the person requesting the review to provide evidence as to why the rating should go up. This provides a small barrier to requesting, and makes the review process easier for the reviewer.

**Comment by wtbarnes** [comment]
Should we add a reevaluation pull request template? If so this would need to provide justification for the reevaluation request and could be something like a diff between the reviewed and current state.

**Comment by nabobalis** [comment]
I added a rough draft of a template in https://github.com/sunpy/sunpy.org/pull/244/files
