### ISSUE TITLE
Main site doesn't load source-sans font

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy.org#245]
This has been bugging me for ages - the main site (e.g. https://sunpy.org/project/affiliated) doesn't seem to load the source-sans font, so it falls back on Helvetica, which makes it look different to the `sunpy` docs. The `.css` in the docs has
```
@import url('https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,900');
```
but no such line is in the main website css. To fix this I can't work out where the main website css is generated from though...

**Comment by nabobalis** [comment]
It should get it from the theme.

**Comment by dstansby** [comment]
Hmm, it doesn't seem to be pulling through the font import then.

**Comment by nabobalis** [comment]
Either a bug in the theme or something we setup incorrectly for the website.

**Comment by nabobalis** [comment]
Does it even work for the docs?

**Comment by nabobalis** [comment]
Looking at the website, the resulting CSS seemed to be squashed.

**Comment by dstansby** [comment]
Yeah, works fine locally for me (building using sphinx). I guess it's something netlify does to the resulting site that unintentionaly removes the font import in the css?

**Comment by nabobalis** [comment]
Yeah, I can't seem to find the import in the resulting CSS.

**Comment by nabobalis** [comment]
Maybe if we can turn off asset optimization on the deploy side @Cadair

**Comment by Cadair** [comment]
I think I have fixed this can you check?

**Comment by nabobalis** [comment]
Works for me.

**Comment by dstansby** [comment]
🎉 amazing, thanks!
