### ISSUE TITLE
Double check "version reviewed" for affiliated packages is correct

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy.org#247]
#244 added the "version reviewed" category to the affiliated packages template category. In the case of aiapy, the listed version is actually not correct as it was reviewed at v0.1 and not v0.2. The current version is v0.2. We should double check to make sure that the listed versions are those that the packages were actually reviewed at.

**Comment by nabobalis** [comment]
I took the lastest version I could find on the repo. Only aiapy has had a recent release so I would expect that to be the only one that needs changing.
