### ISSUE TITLE
Use the new frontmatter support in ablog and document using MyST for blog posts

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy.org#251]
https://github.com/sunpy/ablog/pull/69 and #250 etc

**Comment by Cadair** [comment]
If we do this we should also add a markdown blog post test file to ablog

**Comment by kakirastern** [comment]
Let me do that

**Comment by kakirastern** [comment]
This issue makes me think of a old-school RPG game where I am led through a maze, like **Dungeons & Dragons** on some good-old Nintendo console... (No direct reference to **NDCube** has been made in the process.) 

Am going to open a PR in https://github.com/sunpy/ablog soon.

**Comment by kakirastern** [comment]
I reckon I am supposed to make a PR here, am on it now.

**Comment by kakirastern** [comment]
While I am at it I should update the `README.md` doc as well...
