### ISSUE TITLE
Install link broken on sunpy home page

### ISSUE THREAD

**Issue by ebuchlin** [sunpy/sunpy.org#264]
### Description

On the [sunpy home page](https://sunpy.org/), "Install SunPy" points to https://docs.sunpy.org/en/stable/guide/installation/index.html (Error 404) while the sunpy/sunpy installation instructions are at https://docs.sunpy.org/en/stable/guide/installation.html .

**Comment by nabobalis** [comment]
Thanks for the report, I will fix this now.
