### ISSUE TITLE
`sunpy-soar` affliated package application

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy.org#273]
## Package Details

- Package name: `sunpy-soar`
- Maintainer(s): David Stansby
- Repository: https://github.com/dstansby/sunpy-soar
- Documentation link: https://github.com/dstansby/sunpy-soar/blob/main/README.rst
- PyPI link (if applicable): https://pypi.org/project/sunpy-soar/
- Continuous integration link(s): https://github.com/dstansby/sunpy-soar/actions/workflows/python-test.yml
- Link to Code of Conduct or page describing adopted Code of Conduct: https://sunpy.org/coc, linked from the top of https://github.com/dstansby/sunpy-soar/blob/main/README.rst

## Description of Package
`sunpy-soar` is a plugin to `sunpy.net.Fido` to search for and download data from the Solar Orbiter archive (SOAR).

## Editor Submission Checklist

- [x] Is the submission appropriate (compatible with the SunPy CoC)?
- [x] Does the project have an [appropriate license](https://opensource.org/licenses/)?
- [x] Is the project in an online version control system?
- [x] Does the project provide a Python interface?
- [x] Is the project on PyPI?
- [x] Is the project useful to the solar physics community?
- [x] Version that was reviewed (tag or commit hash)

## Instructions to Reviewer

Please copy the following and select the ranking for each criteria, the full review criteria can be found here:

```
* Functionality           : General Package / Specialized Package / Not Relevant
* Integration             : Well integrated / Partially Integrated / Minimal Integration
* Documentation           : Extensive / Some / Little
* Testing                 : Excellent / Good / Needs Work
* Duplication             : None / Some / Major
* Community               : Excellent / Good / Needs Work
* Development Status      : Stable / Subject to Change / Low Activity / Needs Work
```

**Comment by wtbarnes** [comment]
@hayesla would you be willing to provide a review for this?

**Comment by hayesla** [comment]
Yes I can do this! I'll get on it next week

**Comment by Cadair** [comment]
@hayesla ping ;)

**Comment by nabobalis** [comment]
Do we want to do this or just merge it into core for 4.1?

**Comment by Cadair** [comment]
Let's do this, and we can merge it into core when it and we are ready.

**Comment by hayesla** [comment]
yes sorry I will get on this! super hectic until the solar orbiter meeting next week, but I'll try fit it in

**Comment by wtbarnes** [comment]
@hayesla you still up for reviewing?

**Comment by hayesla** [comment]
* Functionality           : General Package 
* Integration             : Well integrated 
* Documentation           : Some/Little
   - on the documentation side of things, it could be nice to include more docs, examples
* Testing                 :  Good 
* Duplication             : None 
  - (I'm aware that some of the data is available through the VSO (e.g. for some EUI but there is no duplication for querying the SOAR)
* Community               : Excellent 
* Development Status      : Stable

**Comment by hayesla** [comment]
sorry for the delay in reviewing this! All looks great from my end. Is there anything in particular I need to do? 
Also in regards to the `Documentation` criteria - I recognise that sunny-soar does not need extensive documentation as it extends the Fido functionality, but some higher level docs about the SOAR or how its currently working (which would help with oncoming future developers) would be nice (but not blocking here).

**Comment by wtbarnes** [comment]
Thanks! This is great. Would you mind doing two things:

1. Say which version of the code you reviewed and 
2. open an issue regarding your note about the docs

Given this very positive review, I am going to accept `sunpy-soar` as a SunPy affiliated package and ask @dstansby to open up a PR to add `sunpy-soar` to the website.

**Comment by dstansby** [comment]
@wtbarnes I can open a PR. I can also release a new version at the commit that @hayesla reviewed if that's helpful so there's a version number and not a commit hash on the affiliated package list?

**Comment by wtbarnes** [comment]
If you don't mind doing a release, that would be great!

**Comment by dstansby** [comment]
Made a new release, and opened a PR to add to the website. Thanks @hayesla for taking the time to review!

**Comment by ayshih** [comment]
Sorry for the lateness of this question, but has there been discussion about the naming convention?  Why is this `sunpy-soar` and not `sunkit-soar`?

**Comment by dstansby** [comment]
🤷 because that's what I decided to call it
