### ISSUE TITLE
Improvements to the Affiliated package page

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy.org#274]
I went to https://sunpy.org/project/affiliated.html# looking for how to apply for a package to be affiliated, and there is no info at the top. There is info further down, but it was a bit hard for me to find and not obvious so I propose:

- Splitting the page into two (a list of affiliated packages, and applying to become affiliated)
- Putting a link to the second page at the top of the first

**Comment by Cadair** [comment]
Sounds good.

**Comment by nabobalis** [comment]
Other improvements to make/look into:

Explain the benefits more.
Add a list of software that aren't affiliated packages but with the aim of improving discoverability. Maybe another page.
Consider splitting up the page into two: List of current AFs and the review page.
Finish off re-review template.

**Comment by wtbarnes** [comment]
It would also be great to add some info about how to package/release an affiliated package, e.g. like https://packaging-guide.openastronomy.org/en/latest/index.html. It might even be nice to have a sunpy-specific version of that page...
