### ISSUE TITLE
Add "Road Map discussion" to 2022 Coordination Meeting Agenda

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy.org#309]
### Description

We need to add a discussion of the project roadmap to the agenda, either for Tuesday or Thursday afternoon in the last slot. In this discussion, we should hammer out what the project roadmap should be as well as take stock of what the current direction of the project is.

**Comment by nabobalis** [comment]
Previous attempts: https://github.com/sunpy/roadmap
