### ISSUE TITLE
Coordination meeting schedule should be in .5 or 1 hour blocks, not .75

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy.org#310]
### Description

Currently, everything is scheduled in 45 minute blocks which doesn't make any sense and makes all of time boundaries between sessions on the 15th and 45th minute.

**Comment by nabobalis** [comment]
:( poor 0.75 no one likes it.

**Comment by nabobalis** [comment]
Call we decided on 30 minute blocks.
