### ISSUE TITLE
Blog post summarizing the 2022 coordination meeting

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy.org#329]
We took a copious amount of notes during the coordination meeting last week in Dublin. They've now been copied into the [wiki](https://github.com/sunpy/sunpy/wiki/Coordination-Meeting-2022-Notes). We (and by that I mean mostly me) should write a blog post that summarizes what we talked about and the important points that came out of the meeting. This is both for the benefit of the wider community (i.e. to let people know about where the project is headed) and ourselves to have a better understanding of what our action items should be coming out of the meeting.

I'm going to get a start on this ASAP before the meeting starts to leak out of my head.

**Comment by dstansby** [comment]
Close since the meeting has probably leaked out of your head by now?
