### ISSUE TITLE
sunkit-instruments affiliated package

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy.org#335]
## Package Details

- Package name: sunkit-instruments
- Maintainer(s): The SunPy Project
- Repository: https://github.com/sunpy/sunkit-instruments
- Documentation link: https://docs.sunpy.org/projects/sunkit-instruments/
- PyPI link (if applicable): https://pypi.org/project/sunkit-instruments/
- Continuous integration link(s): https://dev.azure.com/sunpy/sunkit-instruments/_build?definitionId=15&_a=summary
- Link to Code of Conduct or page describing adopted Code of Conduct: Same as SunPy

## Description of Package

Stores instrument code that does not belong to a package that is maintained by the instrument teams. 

## Editor Submission Checklist

- [x] Is the submission appropriate (compatible with the SunPy CoC)?
- [x] Does the project have an [appropriate license](https://opensource.org/licenses/)?
- [x] Is the project in an online version control system?
- [x] Does the project provide a Python interface?
- [x] Is the project on PyPI?
- [x] Is the project useful to the solar physics community?
- [x] Version that was reviewed (tag or commit hash)

## Instructions to Reviewer

Please copy the following and select the ranking for each criteria, the full review criteria can be found here:

```
* Functionality           : General Package / Specialized Package / Not Relevant
* Integration             : Well integrated / Partially Integrated / Minimal Integration
* Documentation           : Extensive / Some / Little
* Testing                 : Excellent / Good / Needs Work
* Duplication             : None / Some / Major
* Community               : Excellent / Good / Needs Work
* Development Status      : Stable / Subject to Change / Low Activity / Needs Work
```

**Comment by Cadair** [comment]
@dstansby You up for doing this review?

**Comment by dstansby** [comment]
* Functionality           : General Package
* Integration             : Partially Integrated
* Documentation           : Good
* Testing                 : Excellent
* Duplication             : None
* Community               : Needs Work
* Development Status      : Low Activity

## Notes
### Integration
I've opened a bunch of issues on the repostory. Most of the integration improvements that could be made are returning astropy tables from functions where they currently return dicts. There's also a few areas where a standard time object or unit object should be accepted as input/output.

### Docs
API docs are good (with some small gaps here or there). There is only a single example for the whole library. There are no guides or tutorials for each sub-package.

### Community
I cannot find a code of conduct anywhere obvious, either in the repository or linked in the documentation. Otherwise all the other community criteria are met.

Any questions about my review let me know - if any of the above points are improved, I would be very happy to re-review.

**Comment by Cadair** [comment]
> I cannot find a code of conduct anywhere obvious

I don't know how we make the fact clear that all sunpy maintained packages follow the sunpy CoC. The CoC is linked from the sidebar in the GH repo (as it inherits from the org).

**Comment by dstansby** [comment]
I've just spotted that, but given I was actively looking for a CoC and couldn't find one I think it needs to be more obvious. Places I looked were:
- A file in the repository (code_of_conduct.rst or similar)
- `README.md`
- The documentaiton landing page

**Comment by Cadair** [comment]
:+1: This probably applies to more than just sunkit-instruments.

The file in the repo is a big :-1: from me, we do not want to be maintaining more than one copy of the CoC text. The canonical version is here: https://github.com/sunpy/.github/blob/main/CODE_OF_CONDUCT.md which is built into the website here: https://sunpy.org/coc we should link to that in the readme and docs for all packages of ours.

**Comment by Cadair** [comment]
Actually I am also :-1:  on just throwing it in the docs given we already have it in the nav bar. We should probably add it to the theme in the footer as we have discussed elsewhere.

**Comment by Cadair** [comment]
I don't think we have really documented how exactly we handle responses to reviews, but given https://github.com/sunpy/sunkit-instruments/pull/78 and the fact we do actually have a CoC, will you re-review?

**Comment by wtbarnes** [comment]
@dstansby Given the responses above, are you willing to re-review or does your current review still stand?

**Comment by dstansby** [comment]
I forgot to put the verson reviewed in my original review, but I reviewed v0.3.0. It seems like there hasn't been an updated release with any changes, but if a new release is made I would be happy to re-review.

**Comment by Cadair** [comment]
[v0.3.1](https://pypi.org/project/sunkit-instruments/0.3.1/) is now released if you could re-review that.

**Comment by dstansby** [comment]
- Functionality : General Package
- Integration : Partially Integrated
- Documentation : Good
- Testing : Excellent
- Duplication : None
- Community : Good
- Development Status : Low Activity

Version reviewed: v0.3.1

**Comment by wtbarnes** [comment]
Given the scores, `sunkit-instruments` has passed the review and can now be added to the webpage as an affiliated package.
