### ISSUE TITLE
Add sunkit-instruments link to drop down documentation

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy.org#356]
### Description
We should add sunkit-instriments to the drop down "Documentation" on the sunpy landing page

such as here:
<img width="1222" alt="Screenshot 2023-02-10 at 16 13 52" src="https://user-images.githubusercontent.com/4620298/218127119-e2630cb9-3f30-40ac-a7a8-ede9e6aae3d1.png">

I couldnt figure our where in the repo these are linked - can someone point me in the right direction?

**Comment by nabobalis** [comment]
I will fix this and do a release.

**Comment by nabobalis** [comment]
PR merged, theme update has been tagged. Should see this rolling out over night.
