### ISSUE TITLE
Video carousel not providing a user-friendly experience. 

### ISSUE THREAD

**Issue by bradyblough** [sunpy/sunpy.org#383]
### Description

Steps to Reproduce:

Go to sunpy.org/about/mission

Click the play button on a video in the carousel, and the video should start playing. However, clicking the carousel arrow to go to the next video does not stop the current video from playing, which can lead to multiple videos playing at the same time.

Making matters worse, using the mouse to pause a video switches to the next video because the "next video trigger" is on top of the pause button, so the only way of stopping a video is to use the carousel arrows to scroll to the video that's playing and press the Spacebar on the keyboard.
 
It seems as though this could be implemented in a more user-friendly way.  :)

**Comment by Cadair** [comment]
I got rid of the carousel completely in the redesign, so closing.

Thanks for opening an issue @bradyblough
