### ISSUE TITLE
pfsspy to sunkit-magex 

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy.org#403]
Do we need to review or can we rename the package and go from there?

**Comment by Cadair** [comment]
I would suggest we mark pfsspy as dead, and review magex. I feel like we should go though the process even if it's own own package with minimal new code. (we want to look like we are doing things properly here).

**Comment by nabobalis** [comment]
Then we should get someone to review it.

**Comment by Cadair** [comment]
Ok, this shouldn't be hard, and I haven't actually written it so here is the review for magex:

## Package Details

- Package name: sunkit-magex
- Maintainer(s): The SunPy Project
- Repository: https://github.com/sunpy/sunkit-magex
- Documentation link: https://docs.sunpy.org/projects/sunkit-magex/
- PyPI link (if applicable): https://pypi.org/project/sunkit-magex/
- Continuous integration link(s): https://github.com/sunpy/sunkit-magex/actions
- Link to Code of Conduct or page describing adopted Code of Conduct: https://github.com/sunpy/sunkit-magex/tree/v1.0.0rc1?tab=coc-ov-file#readme

## Description of Package

A magnetic field extrapolation package spun out of pfsspy.



## Package Review

## Editor Submission Checklist

- [x] Is the submission appropriate (compatible with the SunPy CoC)?
- [x] Does the project have an [appropriate license](https://opensource.org/licenses/)?
- [x] Is the project in an online version control system?
- [x] Does the project provide a Python interface?
- [x] Is the project on PyPI?
- [x] Is the project useful to the solar physics community?
- [x] Version that was reviewed (tag or commit hash) 1.0.0(rc1)

**Comment by Cadair** [comment]
* Functionality           : ![](https://img.shields.io/badge/Specialized_Package-brightgreen.svg)
* Integration             : ![Partial Integration](https://img.shields.io/badge/Partial_Integration-orange.svg)
* Documentation           : ![Extensive](https://img.shields.io/badge/Extensive-brightgreen.svg)
* Testing                 : ![Excellent](https://img.shields.io/badge/Excellent-brightgreen.svg)
* Duplication             : ![None](https://img.shields.io/badge/None-brightgreen.svg)
* Community               : ![Excellent](https://img.shields.io/badge/Excellent-brightgreen.svg)
* Development Status      : ![Stable](https://img.shields.io/badge/Stable-brightgreen.svg)
