### ISSUE TITLE
Submit `irispy-lmsal` as an affiliated package

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy.org#414]
## Package Details

- Package name: irispy-lmsal
- Maintainer(s): Nabil Freij (@nabobalis)
- Repository: https://github.com/LM-SAL/irispy-lmsal 
- Documentation link: https://irispy-lmsal.readthedocs.io/en/stable/ 
- PyPI link (if applicable): https://pypi.org/project/irispy-lmsal/
- Continuous integration link(s): https://github.com/LM-SAL/irispy-lmsal/actions
- Link to Code of Conduct or page describing adopted Code of Conduct: errrrrrrrrrr

## Description of Package

A Python package that provides the tools to read in and analyze data from the IRIS solar-observing satellite.

## Editor Submission Checklist

- [x] Is the submission appropriate (compatible with the SunPy CoC)?
- [x] Does the project have an [appropriate license](https://opensource.org/licenses/)?
- [x] Is the project in an online version control system?
- [x] Does the project provide a Python interface?
- [x] Is the project on PyPI?
- [x] Is the project useful to the solar physics community?
- [x] Version that was reviewed: v0.2.0

## Instructions to Reviewer

Please copy the following and select the ranking for each criteria, the full review criteria can be found here:

```
* Functionality           : General Package / Specialized Package / Not Relevant
* Integration             : Well integrated / Partially Integrated / Minimal Integration
* Documentation           : Extensive / Some / Little
* Testing                 : Excellent / Good / Needs Work
* Duplication             : None / Some / Major
* Community               : Excellent / Good / Needs Work
* Development Status      : Stable / Subject to Change / Low Activity / Needs Work
```

**Comment by Cadair** [comment]
@nabobalis Thanks for the submission. The package looks good and it's great to see more officially supported instrument packages emerging. My review is below, the only reason I have marked Community down from excellent is that I can't see a code of conduct in the repo and/or the documentation which is a requirement, if you can add that I will happily bump the review and we can accept irispy-lmsal.

* Functionality           : ![](https://img.shields.io/badge/Specialized_Package-brightgreen.svg)
* Integration             : ![Well integrated](https://img.shields.io/badge/Full_Integration-brightgreen.svg)
* Documentation           : ![Extensive](https://img.shields.io/badge/Extensive-brightgreen.svg)
* Testing                 : ![Good](https://img.shields.io/badge/Good-orange.svg)
* Duplication             : ![None](https://img.shields.io/badge/None-brightgreen.svg)
* Community               : ![Needs Work](https://img.shields.io/badge/Needs_Work-red.svg)
* Development Status      : ![Subject to Change](https://img.shields.io/badge/Subject_to_change-orange.svg)

**Comment by Cadair** [comment]
With that change, here is the final review:

* Functionality           : ![](https://img.shields.io/badge/Specialized_Package-brightgreen.svg)
* Integration             : ![Well integrated](https://img.shields.io/badge/Full_Integration-brightgreen.svg)
* Documentation           : ![Extensive](https://img.shields.io/badge/Extensive-brightgreen.svg)
* Testing                 : ![Good](https://img.shields.io/badge/Good-orange.svg)
* Duplication             : ![None](https://img.shields.io/badge/None-brightgreen.svg)
* Community               : ![Excellent](https://img.shields.io/badge/Excellent-brightgreen.svg)
* Development Status      : ![Subject to Change](https://img.shields.io/badge/Subject_to_change-orange.svg)

@nabobalis can you push a release after that CoC change and then you want to make the PR to the page with this review?

**Comment by nabobalis** [comment]
I tagged a release: https://github.com/LM-SAL/irispy-lmsal/releases/tag/v0.2.1 

The CI wheels are turning.

**Comment by nabobalis** [comment]
Anything else to be done here?

**Comment by Cadair** [comment]
I need to PR to the site with this and also #431
