### ISSUE TITLE
Affiliated Package Review Request: XRTpy

### ISSUE THREAD

**Issue by joyvelasquez** [sunpy/sunpy.org#431]
## Package Details

- Package name: XRTpy
- Maintainer(s): Joy Veasquez  (@joyvelasquez), Nick Murphy (@namurphy), & Jonathan Slavin (@jslavin)
- Repository: https://github.com/HinodeXRT/xrtpy
- Documentation link: https://xrtpy.readthedocs.io/en/stable/
- PyPI link (if applicable): https://pypi.org/project/xrtpy/
- Continuous integration link(s): https://github.com/HinodeXRT/xrtpy/actions
- Link to Code of Conduct or page describing adopted Code of Conduct: TBA

## Description of Package

XRTpy is a Python package developed to facilitate the analysis of observations from the X-Ray Telescope (XRT) aboard the Hinode spacecraft. It provides specialized tools for processing high-resolution solar corona images and diagnosing coronal temperatures, supporting the research needs of the solar physics community.

## Editor Submission Checklist

- [x] Is the submission appropriate (compatible with the SunPy CoC)?
- [x] Does the project have an [appropriate license](https://opensource.org/licenses/)?
- [x] Is the project in an online version control system?
- [x] Does the project provide a Python interface?
- [x] Is the project on PyPI?
- [x] Is the project useful to the solar physics community?
- [x] Version that was reviewed (tag or commit hash) - v0.4.1

## Instructions to Reviewer

Please copy the following and select the ranking for each criteria, the full review criteria can be found here:

```
* Functionality           : General Package / Specialized Package / Not Relevant
* Integration             : Well integrated / Partially Integrated / Minimal Integration
* Documentation           : Extensive / Some / Little
* Testing                 : Excellent / Good / Needs Work
* Duplication             : None / Some / Major
* Community               : Excellent / Good / Needs Work
* Development Status      : Stable / Subject to Change / Low Activity / Needs Work
```

**Comment by wtbarnes** [comment]
@Cadair Are you up for reviewing this submission?

**Comment by Cadair** [comment]
yep

**Comment by Cadair** [comment]
* Functionality           : Specialized Package
* Integration             : Well integrated
* Documentation           : Some
* Testing                 : Good
* Duplication             : None
* Community               : Needs Work
* Development Status      : Subject to Change

Hi @joyvelasquez thanks a lot for submitting this. If you can add a Code of Conduct (https://github.com/HinodeXRT/xrtpy/issues/10) then I can bump the community rating up and we can add XRTPy to the list.

**Comment by joyvelasquez** [comment]
Hello @Cadair, we've successfully created and merged a Code of Conduct for xrtpy. You can review the details in PR #278: https://github.com/HinodeXRT/xrtpy/pull/278.

**Comment by Cadair** [comment]
Thanks, @joyvelasquez here's my final review. Let me know if you have any questions or comments. I shall open a PR to add you to the table later in the week.

* Functionality           : ![Specialized Package](https://img.shields.io/badge/Functionality-Specialized_Package-brightgreen.svg)
* Integration             : ![Well integrated](https://img.shields.io/badge/Integration-Partial-orange.svg)
* Documentation           : ![Some](https://img.shields.io/badge/Documentation-Good-orange.svg)
* Testing                 : ![Good](https://img.shields.io/badge/Testing-Good-orange.svg)
* Duplication             : ![None](https://img.shields.io/badge/Duplication-None-brightgreen.svg)
* Community               : [Good](https://img.shields.io/badge/Community-Good-orange.svg)
* Development Status      : ![Subject to Change](https://img.shields.io/badge/Development_Status-Subject_to_change-orange.svg)
